version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: desafio
    ports:
      - "5434:5432"
    networks:
      - mynetwork
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://usuario:senha@db/desafio

volumes:
  pgdata:

networks:
  mynetwork: